#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar bar1 &
pgrep -x compton > /dev/null || compton &

bspc monitor -d 1 2 3 4

bspc config border_width 0
bspc config window_gap 15
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

feh --bg-fill ~/Pictures/wallpapers/abstract.png

# prevent cursor from switching to an 'X'
xsetroot -cursor_name left_ptr
